### ISSUE TITLE
ESP-IDF Conversion Tracking

### ISSUE THREAD

**Issue by OttoWinter** [esphome/feature-requests#1414]
Not quite a feature-request, but an progress discussion.

We've been working on making esphome directly target esp-idf on ESP32s (without the arduino middle layer). This has been combined with extensive work to generalize a bunch of hardware abstractions.

Goal: More stability due to directer access to esp-idf (esp-idf looks much more supported than arduino), ability to change sdkconfig

Current state: (see also [esp-idf branch](https://github.com/esphome/esphome/tree/esp-idf))

- [x] Create system so "target platforms" like "esp32" are in their own integration module.
- [x] Convert ESP32 to that modular system
- [x] Convert ESP8266 to that modular system
- [x] Create arduino-independent core abstractions for GPIOPin
- [x] Make esp-idf use those abstractions
- [x] Rewrite esp32 arduino to use them
- [x] Rewrite esp8266 arduino to use them
- [x] Fix the few cases where pins were used directly from the schema
- [x] Re-add support for "arduino-style" pin schema `mode:` setting
- [x] Backport some commonly used functions like millis/yield/etc
- [x] Add ESP-IDF implementation of wifi integration
- [x] Small changes to ESP32 Arduino wifi integrations (new methods)
- [x] Small changes to ESP8266 Arduino wifi integrations (new methods)
- [x] Create an abstraction for Preferences backend
- [x] Implement Preferences for ESP32 Arduino/IDF
- [x] Implement Preferences for ESP8266
- [x] i2c Component
- [x] spi Component
- [x] uart Component
- [x] ota Component (networking part is ready with sockets conversion)
- [x] Convert all `ARDUINO_ARCH_ESPXX` to `#ifdef USE_ESPXX`
- [x] Add new clang-tidy target for esp-idf
- [x] Fix all lint errors

Not in scope:
- Porting some Arduino Libraries we use including:
- `web_server` (and `captive_portal`): `ESPAsyncWebServer` and `AsyncTCP`
- `mqtt`: `AsyncMQTTClient` and `AsyncTCP`

Contributions are welcome! Just create a PR against the `esp-idf` branch

**Comment by OttoWinter** [comment]
Good news! The implementation part of the conversion is pretty much complete now :tada: - all APIs that needed refactoring are now refactored and any compile problems in dependent components fixed, including all automated test compiles/static-analysis.

Now comes the testing... I've not checked the code for if it works in most places, so things might be broken; It looks like Arduino/ESP-IDF do work with some simple configs, but we need to test if this is true even for more complex things like BLE/i2c/spi/uart.

The way I see it the best way forward is now: 
1. ensure no existing stuff is broken (meaning arduino-based ESP32/ESP8266)
2. merge the changes
3. fix any issues with ESP-IDF (for example BLE looks a bit broken)

**Comment by jesserockz** [comment]
One more thing I found today is that ESP32 using IDF no longer has hardware SPI support. This will need to be added at some point. Probably good to split the SPI now similar to I2C and UART using separate classes.

**Comment by grischard** [comment]
Are there already separate issues to follow for the `web_server`, `captive_portal`, `mqtt` etc. features? I tried searching but didn't find any.

**Comment by OttoWinter** [comment]
There is not, indeed would be good to split it up. I will close this as the main idf conversion is done now.
